name: hongyanasst
description: HongyanAsst flutter application.

publish_to: 'none'

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  shared_preferences: ^2.0.12
  chewie: ^1.2.2
  lottie: ^1.2.1
  orientation: ^1.3.0
  adaptive_dialog: ^1.2.0
  flutter_swiper_null_safety: ^1.0.2
  url_launcher: ^6.0.10
  image_picker: ^0.8.4+4
  video_player: ^2.2.7
  transparent_image: ^2.0.0
  cached_network_image: ^3.2.0
  http: ^0.13.4
  webview_flutter: ^3.0.0
  flutter_nested: ^1.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_native_splash: ^1.3.2
  underline_indicator: ^0.0.4
  flutter_statusbarcolor_ns: ^0.4.0
  date_format: ^2.0.5
  web_socket_channel: ^2.1.0
  provider: ^5.0.0
  amap_flutter_map: ^3.0.0
  fluttertoast: ^8.0.8
  flutter_easyloading: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - images/
    - assets/AE_animation/
